### ISSUE TITLE
BENTO - MyJackpot - September 2022 Cashbook

### ISSUE THREAD

**Issue by kolehiyolo-hpl** [kolehiyolo-hpl/projects#17]
### CLIENT'S REQUEST:
- It should run at the same runtime as the event.
- comes in the same theme as the event
- 3 sets each

release datum: 02.03.

Verbatim:
_Regarding the September Cashbook.
Our longterm goal is that we dont have to come up with moodboards and ideas for the cashbooks.
I think it would be cool to give it a try for the september cashbook that you guys come up with some ideas for the design.
What do you thinlk?_

----------------------------------
### REQUIREMENTS:
- [x] Cashbook Cover
- - [x] Initial design
- - [x] Localized
- [x] Booster Packs
- - [x] Initial design
- - [x] Localized
- [x] Set Icons (3)
- - [x] Icon 1
- - [x] Icon 2
- - [x] Icon 3
- [x] Trophy Shop Icons
- - [x] Initial design
- - [x] Localized
- [x] Dividers
- - [x] Initial design
- - [x] Localized
- [x] Unboxing Headlines
- - [x] Initial design
- - [x] Localized

**Comment by kolehiyolo-hpl** [comment]
### 📝TASK: 2022-05-19-01 - Initial Design (Althea Itona)
Feedback:
_No feedback_

---------------------------------------
Requirements:
- [ ] Brainstorm muna nung themes
- [ ] Create moodboard
- [ ] Design cover kung kaya

**Comment by kolehiyolo-hpl** [comment]
### ✔SUBMISSION: 2022-05-19-01 - Initial Design (Althea Itona) 8 HRS
- [x] Brainstorm muna nung themes
- [x] Create moodboard
- [x] Design cover kung kaya

Storage: https://www.dropbox.com/sh/nkxfr1svbuuypxd/AABQXiFqQc3K8F-jNEjbJRApa?dl=0

**Comment by kolehiyolo-hpl** [comment]
### 📝TASK: 2022-05-20-01 - Revision & Design (Althea Itona)
Feedback:
_great job on the moodboard and designs :100:
i am very happy with it! :slightly_smiling_face:
colors, mood, vibe - everything on point!
may i ask you to have a look at these really small adjustments, please.
thank you and see you tomorrow!_

https://www.dropbox.com/sh/nkxfr1svbuuypxd/AABQXiFqQc3K8F-jNEjbJRApa?dl=0

---------------------------------------
Requirements:
- [ ] Revise cashbook cover as per image
- [ ] Proceed with other assets

**Comment by kolehiyolo-hpl** [comment]
### ✔SUBMISSION: 2022-05-20-01 - Revision & Design (Althea Itona) 8 HRS
Requirements:
- [x] Revise cashbook cover as per image
- [x] Proceed with other assets

Storage: https://www.dropbox.com/sh/80vyhhog2px87pb/AABLiEdDLrk6eYSJDvd7CBLHa?dl=0

**Comment by kolehiyolo-hpl** [comment]
### 📝TASK: 2022-05-23-01 - Design (Kevin Eleazer B. Silvestre)
Feedback:
_No feedback_

---------------------------------------
Requirements:
- [ ] Make icons
- - [ ] Harvest time
- - [ ] Farm Grown (wag na pala to)
- - [ ] Cozy Day
- - [ ] Pumpkin spiced
- [ ] Make trophy shop

**Comment by kolehiyolo-hpl** [comment]
### ✔SUBMISSION: 2022-05-23-01 - Design (Kevin Eleazer B. Silvestre) 8 HRS
Requirements:
- [x] Make icons
- - [x] Harvest time
- - [x] Farm Grown (wag na pala to)
- - [x] Cozy Day
- - [x] Pumpkin spiced
- [ ] Make trophy shop

Storage: https://www.dropbox.com/sh/nkxfr1svbuuypxd/AABQXiFqQc3K8F-jNEjbJRApa?dl=0

**Comment by kolehiyolo-hpl** [comment]
### 📝TASK: 2022-05-24-01 - Design (Kevin Eleazer B. Silvestre)
Feedback:
_the trophy shop assets do need an additional check for characters. for example the CS translation does have a not supported character.
the pumpkin spiced icon could have a bigger pumpkin, please.
try to work with overlapping elements to have it more interesting, please.
cozy day and harvest time are too similar in terms of colors on the type. try to find different colors for cozy day, please.
harvest time is fine and approved.
excited to see the applied feedback for the boosterpack, tomorrow :)_

https://www.dropbox.com/sh/dghhifoykvdczch/AADpga_90bIMQWVnC7KsoIEla?dl=0

<img width="396" alt="image (1)" src="https://user-images.githubusercontent.com/103549927/169985821-c43abc9a-fd12-4a7a-864b-34725d4c97a9.png">
<img width="396" alt="image (1)" src="https://user-images.githubusercontent.com/103549927/169985946-2be69db5-d84e-4b0a-a97a-da5cae54a347.png">
<img width="395" alt="image" src="https://user-images.githubusercontent.com/103549927/169985828-f62ef995-a2b6-4cca-b6a1-b544881b9596.png">


---------------------------------------
Requirements:
- [x] Check Trophy Shop Assets for Character issues with loca
- [x] Set Icons Revisions
- - [x] Cozy Day needs different colors from Harvest Time
- - [x] Pumpkin spiced could have a bigger pumpkin and more overlapping elements for interest
- [x] Booster Pack revision as per the image

**Comment by kevineleazers** [comment]
### ✅SUBMISSION: 2022-05-24-01 - Design (Kevin Eleazer B. Silvestre) 8 HRS
Storage: https://drive.google.com/file/d/1AOIzn7D8yUC0LeYydRjpK0kT63d87cDW/view?usp=sharing
